apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pharm-sim-route
  namespace: excaperoom-ohtu-s2026
  labels:
    app: pharm-sim
    type: external
spec:
  host: excaperoom-ohtu-s2026-pharm-sim.apps.okd-cs-test-0.k8s.cs.helsinki.fi
  to:
    kind: Service
    name: pharm-sim-svc
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
