apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -production

images:
  - name: dominicnygard/pharm-sim
    newTag: release

patches:
  - path: deployment-patch.yaml
  - path: route-patch.yaml
