apiVersion: route.openshift.io/v1
kind: Route

metadata:
  name: pharm-sim
  labels:
    router: external

spec:
  host: excaperoom-ohtu-s2026-pharm-sim.ext.okd-cs-test-0.k8s.cs.helsinki.fi
  to:
    kind: Service
    name: pharm-sim-staging
